#!/bin/sh
cd ~/Projects/hzchris

echo "Executing backup configs to github script. Date: `date +%Y-%m-%d`"

if [[ $(git status -s) ]]
then
  echo "Following files were changed!"
  git status -s
  git add --all
  git commit -m "Regular update on: `date +%Y-%m-%d`"
  git push
else
  echo "Nothing changed!"
fi
  
